mongodb:
  uri: localhost:27017

spring:
  security:
    user:
      password: admin
      name: admin
      roles: ADMIN

server:
  port: 8080

eng-card:
  data:
    init-dao:
      enabled: true

springfox:
  documentation:
    auto-startup: true